# Generated by Django 6.0.1 on 2026-01-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favoriteitem',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='favoriteitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='author',
        ),
        migrations.AddField(
            model_name='product',
            name='owner_id',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reviews',
            name='user_id',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='FavoriteItem',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
