# Generated by Django 6.0.1 on 2026-01-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_reviews_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner_id',
            field=models.SmallIntegerField(),
        ),
    ]
